10 accessibility issues
datasciencecampus/coding-in-the-open pull request #13
Opened 2023-05-22 12:52 UTC by r-leyshon

Mostly fixes #10 

All accessibility errors resolved.

Following warnings persist, I'll record a separate issue with more detail to catch these:
5 Alerts
* 		2 X Redundant link
* 		2 X Tabindex
* 		1 X YouTube video

The YouTube video alert should be tolerated.

2023-05-23 15:15 UTC, merged

2023-05-23 15:17 UTC, ethan-moss requested changes
All runs as expected, and was able to render the pages. 

Running accessibility checks:
- Fixes implemented to resolve immediately resolvable accessibility issues has worked - nicely detected and implemented!
- Picked same subset of remaining issues referenced within the PR - OK for these to be resolved at a later date.
- I've added some further comments into this review. Most relate to additional accessibility issues that were detected during this review, and some are just questions. These could do with being resolved/answered before merging - in case they are immediately resolvable. Let me know what you think.

2023-05-24 08:26 UTC, r-leyshon commented on _quarto.yml
> -    logo-alt: Data Science Campus logo
Great question, may not have been very clear in the commit messages. There's a problem with the `logo-alt` attribute not rendering the alt text, leading to an accessibility error. The current setup fixes that. I agree it's better to have it in its original position and will raise an issue capturing this.

2023-05-24 08:29 UTC, r-leyshon commented on _quarto.yml
>        - index.qmd
Ah, this looks like a quick fix. Great spot. Will handle it in a dedicated branch.

2023-05-24 08:31 UTC, r-leyshon commented on _quarto.yml
>    page-footer:
I think this is referring to the social media buttons? Just for comparison, here's the wave check on the current pages deployment and the error we discussed is not flagged. I wonder if it's a browser compitability issue? For reference, this is tested on Chrome and if its the best browser to view this guidance on we should include a statement about it in the guidance. Can you confirm what browser you've been testing on @ethan-moss ?

2023-05-24 08:38 UTC, r-leyshon commented on index.qmd
> -Open-source development does bring with it some additional considerations and risks [@GASOpenSource]. As a result, there are scenarios in which opening all or parts of a codebase may not be possible
Bit confused here. The lines you referenced seem to refer to the boxes in the img below. I don't immediately see a problem with the formatting, please advise if I've misunderstood anything:
<img width="799" alt="image" src="https://github.com/datasciencecampus/coding-in-the-open/assets/49126943/f566cf72-a33d-4a00-9021-f9eed55292fc">

2023-05-24 08:44 UTC, ethan-moss commented on index.qmd
> -Open-source development does bring with it some additional considerations and risks [@GASOpenSource]. As a result, there are scenarios in which opening all or parts of a codebase may not be possible
Yes, that's right. It's a very minor point, but the right hand margin is a bit smaller than the top/left/bottom, meaning the text gets very close to the box (see 'be' - line1 in the top box- , and 'or' -line 5 in the bottom box). I think this came about when swapping to the default theme, but I'm not sure. I think it would be good to have more right hand margin, to make it easier to read (and look a little neater).

2023-05-24 08:53 UTC, r-leyshon commented on _quarto.yml
>        - index.qmd
Bah, unresolving this thread. _quarto.yml looks different to what you've reviewed. This is the current version of the code with the logo to the right of the page. This avoids the duplicate url alert for the image, though the sidebar title still causes it as without the logo it renders a link-wrapped title instead - the default behaviour in the docs. I'll try title:none to see if this resolves the situation.

How my YAML appears for context, unsure what's gone wrong here:
```
  margin-header: |
    <a href="https://datasciencecampus.ons.gov.uk/">
      <img src="https://datasciencecampus.ons.gov.uk/wp-content/uploads/sites/10/2017/03/data-science-campus-logo-new.svg" alt="Data Science Campus logo">
    </a>
  twitter-card: 
    site: https://twitter.com/DataSciCampus
  sidebar:
```

2023-05-24 09:15 UTC, ethan-moss commented on _quarto.yml
>    page-footer:
Sure, it's Chrome too, which suggests it may not be a Chrome issue. I wonder if this conflict comes from the Wave versions we're using? I'm currently running the Wave Chrome extension version 3.2.3.

2023-05-24 09:16 UTC, r-leyshon commented on index.qmd
> -Open-source development does bring with it some additional considerations and risks [@GASOpenSource]. As a result, there are scenarios in which opening all or parts of a codebase may not be possible
Right that's clarified it for me. Yes happy to convert to an issue.

2023-05-24 09:21 UTC, r-leyshon commented on _quarto.yml
>    page-footer:
3.2.3 also. How strange. But you're on windows and I'm on Mac? Need to get to the bottom of this one as I'd expect many of the target audience may engage with it on Windows.