61 never open guidance
datasciencecampus/coding-in-the-open pull request #70
Opened 2023-09-25 09:32 UTC by r-leyshon

## Description/Contribution Summary

Fixes #61 

## Motivation and Context

Guidance has now incorporated feedback from ONS FoI team & DSC colleagues in Email chain.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Accessibility

No errors, one known alert to tolerate - A link to a PDF document is present.

## Advice for reviewer

## Checklist:

- [X] I have read the [CONTRIBUTING.md](../../CONTRIBUTING.md) guidance for raising pull requests  
- [X] I have followed the intended structure of this project
- [X] I have performed a self-review
- [X] This pull-request meets the accessibility guidance provided in the contributing guidance.

## Additional comments

2023-10-09 07:52 UTC, NicciPotts commented
> @NicciPotts @ethan-moss @TSGreen Hi all, I just resolved a small merge conflict in the qmd YAML. Does anyone have a couple of hours to review this? Would need draft checking for typos etc and some more opinionated feedback on language used and points made would be welcome, but not required.

Hi @r-leyshon I've got a really short week this week (this afternoon and tomorrow) but if I get my model running tomorrow I should be able to give this a look. *IF*

2023-10-10 17:39 UTC, TSGreen requested changes
Hi Rich, I had a read and made a bunch of small edits (largely in relation to formatting for rendering), which I will push up shortly and I've added a couple of specific comments for things I wasn't sure about.

2023-10-10 17:39 UTC, TSGreen commented on never-open/explanation.qmd
> +main branch. Checks and balances should be proportionate to the risk involved
The two sentences that start with "ensure" don't really fit into narrative of the wider paragraph

2023-10-10 17:41 UTC, TSGreen commented on never-open/explanation.qmd
> +the risk and scope of potential FoI requests. This article intends to help the
It in unclear in the current version of the page that the FoI team were asked questions and which part of the page this refers to. So might be worth updating this.

2023-10-13 12:41 UTC, r-leyshon commented
Some good catches in that latest commit @TSGreen . I don't know what's going on with the referencing syntax, but I find sometimes it accepts `some text@ref_with_no_space` and on other occasions trying to do that completely breaks all references in the document. I can see you must have encountered this problem when locally renderring. Possibly worth raiseing a bug report on the quarto repo if only I could reproduce the difference.

2023-10-25 07:49 UTC, r-leyshon commented on never-open/explanation.qmd
> +the risk and scope of potential FoI requests. This article intends to help the
Thanks again @TSGreen , I've now implemented changes in response to your comments. Please review and merge if appropriate.

2023-10-25 09:00 UTC, TSGreen approved these changes
Looks good! Will merge

2023-10-25 09:01 UTC, merged